// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/home.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    PublicFooter: typeof import('./src/components/PublicFooter.vue')['default']
    PublicHeader: typeof import('./src/components/PublicHeader.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TInput: typeof import('tdesign-vue-next')['Input']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
